version: "3"

services:
  backend:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: 10.0.1.7  # IP de la base de données centrale MariaDB
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      DB_USER: mariadb
      DB_PASSWORD: admin
      DB_NAME: default  # Nom de la base de données

  configurator:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
    environment:
      DB_HOST: 10.0.1.7  # IP de la base de données centrale MariaDB
      DB_PORT: "3306"
      DB_USER: mariadb
      DB_PASSWORD: admin
      DB_NAME: default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 10.0.1.7:3306;  # Attente pour la base de données centrale

  # db:
  #   image: mariadb:10.6
  #   container_name: db_feature_cicd
  #   networks:
  #     - frappe_network
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MARIADB_ROOT_PASSWORD: admin
  #   volumes:
  #     - db_feature_cicd_data:/var/lib/mysql  # Volume isolé pour cette base de données spécifique

  frontend:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-feature-cicd.rule=Host(`cwo848sgsowsk04o40w4ckwg.161.97.174.134.sslip.io`)"
      - "traefik.http.services.erpnext-feature-cicd.loadbalancer.server.port=8080"

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db_data:   # Volume pour la base de données spécifique à la branche
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
