version: "3"

services:
  backend-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites-feature-new:/home/frappe/frappe-bench/sites
      - logs-feature-new:/home/frappe/frappe-bench/logs
    environment:
      - MYSQL_ROOT_PASSWORD=h123@
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=456
      - MYSQL_HOST=db-feature-new  # Conteneur DB spécifique à la branche
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=db-feature-new  # Base de données spécifique à la branche
      - MYSQL_URL=mysql://mariadb:456@db-feature-new:3306/db-feature-new

  db-feature-new:
    image: mariadb:10.6
    networks:
      - backend_network
    environment:
      MYSQL_ROOT_PASSWORD: h123@
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: 456
      MYSQL_DATABASE: db-feature-new  # Création d'une base de données spécifique à la branche
    volumes:
      - dbdata-feature-new:/var/lib/mysql
    networks:
      - backend_network

  configurator-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=h123@
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=456
      - MYSQL_HOST=db-feature-new
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=db-feature-new
      - MYSQL_URL=mysql://mariadb:456@db-feature-new:3306/db-feature-new
    volumes:
      - sites-feature-new:/home/frappe/frappe-bench/sites
      - logs-feature-new:/home/frappe/frappe-bench/logs

  create-site-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 200 db-feature-new:3306;
        wait-for-it -t 200 redis-cache-feature-new:6379;
        wait-for-it -t 200 redis-queue-feature-new:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";

  frontend-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    depends_on:
      - websocket-short-feature-new:
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend-feature-new:8000
      FRAPPE_SITE_NAME_HEADER: feature-new.local
      SOCKETIO: websocket:9000
    volumes:
      - sites-feature-new:/home/frappe/frappe-bench/sites
      - logs-feature-new:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-feature-new.rule=Host(\`feature-new.sslip.io\`)"
      - "traefik.http.services.erpnext-feature-new.loadbalancer.server.port=8080"

  queue-long-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites-feature-new:/home/frappe/frappe-bench/sites
      - logs-feature-new:/home/frappe/frappe-bench/logs

  queue-short-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites-short-feature-new:/home/frappe/frappe-bench/sites
      - logs-short-feature-new:/home/frappe/frappe-bench/logs

  redis-queue-short-feature-new:
    image: redis:6.2-alpine
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data-short-feature-new:/data

  redis-cache-short-feature-new:
    image: redis:6.2-alpine
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler-short-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites-short-feature-new:/home/frappe/frappe-bench/sites
      - logs-short-feature-new:/home/frappe/frappe-bench/logs

  websocket-short-feature-new:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    networks:
      - backend_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites-short-feature-new:/home/frappe/frappe-bench/sites
      - logs-short-feature-new:/home/frappe/frappe-bench/logs

networks:
  backend_network:

volumes:
  dbdata-feature-new:  # Volume dédié à la DB spécifique à la branche
  sites-feature-new:    # Volume pour les sites ERPNext de cette branche
  logs-feature-new:     # Volume pour les logs spécifiques à cette branche
