version: "3"

services:
  backend:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs
    environment:
      - MYSQL_ROOT_PASSWORD=hello
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=123
      - MYSQL_HOST=161.97.174.134
      - MYSQL_PORT=5434
      - MYSQL_DATABASE=default
      - MYSQL_URL=mysql://mariadb:123@161.97.174.134:5434/default
  configurator:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      - MYSQL_ROOT_PASSWORD=hello
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=123
      - MYSQL_HOST=161.97.174.134
      - MYSQL_PORT=5434
      - MYSQL_DATABASE=default
      - MYSQL_URL=mysql://mariadb:123@161.97.174.134:5434/default
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - SOCKETIO_PORT=9000
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs

  create-site:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 200 161.97.174.134:5434;
        wait-for-it -t 200 redis-cache:6379;
        wait-for-it -t 200 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";

  frontend:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: site1.local
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-feature-cicd.rule=Host(`feature-cicd.161.97.174.134.sslip.io`)"
      - "traefik.http.services.erpnext-feature-cicd.loadbalancer.server.port=8080"

  queue-long:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs

  queue-short:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data-${BRANCH_SANITIZE}:/data

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs

  websocket:
    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/sites
      - logs-${BRANCH_SANITIZE}:/home/frappe/frappe-bench/logs

volumes:
  db-data-${BRANCH_SANITIZE}:
  redis-queue-data-${BRANCH_SANITIZE}:
  sites-${BRANCH_SANITIZE}:
  logs-${BRANCH_SANITIZE}:
