# Informations de base sur le projet
sonar.projectKey=pro-erpnext
sonar.projectName=pro-erpnext
sonar.scm.provider=git
sonar.sources=.

# Définir le répertoire des sources (Python, JS, Node)
# Répertoire des tests
#sonar.tests=erpnext/tests
# sonar.test.exclusions=**/tests/**
# sonar.exclusions=**/docs/**,**/*.md,**/*.log
# # Analyser le code Python
# sonar.python.version=3.x
# sonar.python.coverage.reportPaths=coverage.xml
# # Analyser le code JavaScript et Node.js
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# # Rapport de qualité du code
# sonar.sourceEncoding=UTF-8
# sonar.verbose=true
# # Logs détaillés pour le débogage
# sonar.log.level=INFO
# # Exclure certains fichiers/dossiers de l'analyse
# sonar.exclusions=**/*.md, **/assets/**, **/translations/**, **/tests/**, **/patches/**, erpnext/demo/**, **/docs/**
# Intégration SCM (Source Code Management)