name: Get Branch Name

on:
  push:
    branches:
      - '**'  # Pour toutes les branches
  pull_request:
    branches:
      - '**'  # Pour toutes les PR

jobs:
  get-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up the branch name script
        id: get-branch-name
        run: |
          # Récupérer le nom de la branche
          if [[ -n "$GITHUB_HEAD_REF" ]]; then
            branch_name="${GITHUB_HEAD_REF}"
          else
            branch_name=$(git rev-parse --abbrev-ref HEAD)
          fi

          # Remplacer "/" par "-"
          branch_name=$(echo "$branch_name" | sed "s/\//-/g")

          # Afficher le nom de la branche et le définir comme variable d'environnement
          echo "Nom de la branche : $branch_name"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV  # Définir la variable d'environnement pour tout le pipeline
          
      - name: Use BRANCH_NAME
        run: |
          echo "La branche est : $BRANCH_NAME"  # Utiliser la variable BRANCH_NAME dans un autre step

      - name: Create .env file with "hello"
        run: |
          echo "IMAGE_NAME=image:latest" >> .env
          echo "REGISTRY_PASSWORD=hello" >> .env
          echo "BRANCH_NAME=ci" >> .env
          cat .env

      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: get-branch-name

    steps:
      - name: Deploy
        run: |
          # curl -X POST "http://161.97.174.134:8000/api/v1/applications/public" \
          #   --header "Authorization: Bearer 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f" \
          #   --header "Content-Type: application/json" \
          #   --data '{
          #     "project_uuid": "v0ggs00w4kgskcksgkgkk8oc",
          #     "server_uuid": "g04w4sg0csocwgocwgkgg44k",
          #     "environment_name": "development",
          #     "git_repository": "https://github.com/Flora24-Yedidya/restful-booker.git",
          #     "git_branch": "feature/cicd",
          #     "ports_exposes": "8081",
          #     "build_pack": "dockercompose",
          #     "name": "test",
          #     "docker_compose_location": "docker-compose.yml",
          #     "docker_compose_custom_build_command": "echo \\\"$REGISTRY_PASSWORD\\\" | docker login ghcr.io -u devofs2 --password-stdin",
          #     "docker_compose_custom_start_command": "docker compose up -d",
          #     "manual_webhook_secret_github": "hello",
          #     "instant_deploy": true
          #   }'
          
          curl -X POST "http://161.97.174.134:8000/api/v1/deploy?uuid=bw004c8c4g8s040wowo8ww4s" \
          --header "Authorization: Bearer 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f" \
          --header "Content-Type: application/json"


