#name: Get Branch Name

on:
  push:
    branches:
      - '**'  # Pour toutes les branches
  pull_request:
    branches:
      - '**'  # Pour toutes les PR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/heads/dev') && !startsWith(github.ref, 'refs/heads/test') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Branch Name
        run: |
          # Récupérer le nom de la branche
          if [[ -n "$GITHUB_HEAD_REF" ]]; then
            branch_name="${GITHUB_HEAD_REF}"
          else
            branch_name=$(git rev-parse --abbrev-ref HEAD)
          fi

          # Remplacer "/" par "-" pour le nom de l'image Docker
          branch_sanitize=$(echo "$branch_name" | sed "s/\//-/g")

          # Définir les variables d'environnement
          echo "Nom de la branche : $branch_name"
          echo "Branch_sanitize : $branch_sanitize"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "BRANCH_SANITIZE=$branch_sanitize" >> $GITHUB_ENV


  deploy-app:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      COOLIFY_URL: https://coolify.ofs.bj
      COOLIFY_API_KEY: 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f
      PROJECT_UUID: "v0ggs00w4kgskcksgkgkk8oc"
      BRANCH_NAME: feature/cicd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install jq
        run: sudo apt-get install jq -y
      
      - name: Set execute permissions
        run: chmod +x .github/scripts/*.sh

      - name: Check app
        run: ./.github/scripts/create_application.sh "$PROJECT_UUID" "$BRANCH_NAME"


      # - name: Create application on Coolify
      #   #if: steps.check_app.outputs.app_exists == 'false'
      #   id: create_app
      #   run: |
      #     APP_UUID=$(./.github/scripts/create_application.sh $PROJECT_UUID $BRANCH_NAME)
      #     echo "APP_UUID=$APP_UUID" >> $GITHUB_ENV

# curl "http://161.97.174.134:8000/api/v1/projects/v0ggs00w4kgskcksgkgkk8oc/development" \
#   --header "Authorization: Bearer 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f" \
#   --header "Content-Type: application/json"

    
      # - name: Deploy application
      #   run: ./.github/scripts/deploy_application.sh ${{ env.APP_UUID }}
    








  # deploy_preprod:
  #   runs-on: ubuntu-latest
  #   needs: [staging]
  #   steps:
  #     - name: 🛎 Checkout Code
  #       uses: actions/checkout@v3

  #     - name: 🚀 Setup SSH key for deploy
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.DEPLOY_KEY }}

  #     - name: 🌐 Deploy to Server via SSH
  #       run: |
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "
  #         cd /home/${{ secrets.DEPLOY_USER }}/app && \
  #           sh deploy.sh
  #           docker-compose ps
  #         "















      # jobs:
#   get-branch-name:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up the branch name script
#         id: get-branch-name
#         run: |
#           # Récupérer le nom de la branche
#           if [[ -n "$GITHUB_HEAD_REF" ]]; then
#             branch_name="${GITHUB_HEAD_REF}"
#           else
#             branch_name=$(git rev-parse --abbrev-ref HEAD)
#           fi

#           # Remplacer "/" par "-"
#           branch_name=$(echo "$branch_name" | sed "s/\//-/g")

#           # Afficher le nom de la branche et le définir comme variable d'environnement
#           echo "Nom de la branche : $branch_name"
#           echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV  # Définir la variable d'environnement pour tout le pipeline
          
#       - name: Use BRANCH_NAME
#         run: |
#           echo "La branche est : $BRANCH_NAME"  # Utiliser la variable BRANCH_NAME dans un autre step

#       - name: Create .env file with "hello"
#         run: |
#           echo "IMAGE_NAME=image:latest" >> .env
#           echo "REGISTRY_PASSWORD=hello" >> .env
#           echo "BRANCH_NAME=ci" >> .env
#           cat .env

#       - name: Upload .env file
#         uses: actions/upload-artifact@v4
#         with:
#           name: env-file
#           path: .env
#           include-hidden-files: true

#   deploy:
#     runs-on: ubuntu-latest
#     needs: get-branch-name

#     steps:
#       - name: Deploy
#         run: |
#           # curl -X POST "http://161.97.174.134:8000/api/v1/applications/public" \
#           #   --header "Authorization: Bearer 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f" \
#           #   --header "Content-Type: application/json" \
#           #   --data '{
#           #     "project_uuid": "v0ggs00w4kgskcksgkgkk8oc",
#           #     "server_uuid": "g04w4sg0csocwgocwgkgg44k",
#           #     "environment_name": "development",
#           #     "git_repository": "https://github.com/Flora24-Yedidya/restful-booker.git",
#           #     "git_branch": "feature/cicd",
#           #     "ports_exposes": "8081",
#           #     "build_pack": "dockercompose",
#           #     "name": "test",
#           #     "docker_compose_location": "docker-compose.yml",
#           #     "docker_compose_custom_build_command": "echo \\\"$REGISTRY_PASSWORD\\\" | docker login ghcr.io -u devofs2 --password-stdin",
#           #     "docker_compose_custom_start_command": "docker compose up -d",
#           #     "manual_webhook_secret_github": "hello",
#           #     "instant_deploy": true
#           #   }'
          
#           curl -X POST "http://161.97.174.134:8000/api/v1/deploy?uuid=bw004c8c4g8s040wowo8ww4s" \
#           --header "Authorization: Bearer 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f" \
#           --header "Content-Type: application/json"


